name: Build and Push Docker Image

on:
  workflow_run:
    workflows: [ "test" ]
    types: [ "completed" ]
    branches: [ "main" ]
    
permissions:
  contents: read
  packages: write
  
jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Directorio con el Dockerfile
          push: true # Empujar la imagen después de construirla
          tags: ghcr.io/jaureliogithub/prj_salary:latest
          #tags: ghcr.io/${{ toLower(github.repository_owner) }}/prj_salary:latest